version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: barbearia-app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: minha_senha
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d