version: '3'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  smart-barber:
    build:
      context: .
    image: rafaelbrunof/smart-barber
    depends_on:
      - postgres
    env_file:
      - .env
    ports:
      - "5000:5000"