version: '3'

services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=click-barber_db'
      - 'POSTGRES_PASSWORD=clbb'
      - 'POSTGRES_USER=clbb'
    ports:
      - '5432:5432'

  backend:
    build:
      context: ./backend
    image: rafaelbrunof/clickbarber-backend
    depends_on:
      - postgres
    ports:
      - "8081:8081"

  frontend:
    build:
      context: ./frontend
    image: rafaelbrunof/smart-barber-frontend
    ports:
      - "3000:3000"