version: '3'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

  backend:
    build:
      context: ./backend
    image: rafaelbrunof/smart-barber-backend
    depends_on:
      - postgres
    env_file:
      - ./backend/.env
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    image: rafaelbrunof/smart-barber-frontend
    ports:
      - "8080:80"