server:
  port: 8081

spring:
  datasource:
    url: ${BD_URL}
    driver-class-name: org.postgresql.Driver
    validation-query: SELECT 1;
    test-on-borrow: true

  jpa:
    packages-to-scan: com.optimiza.clickbarber.model
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    validateMigrationNaming: true
    locations: classpath:db/migration/postgres

jwt:
  secret: secretkeyclickbarbertestespringbootcomjava1234

frontend:
  admin:
    url: ${FRONTEND_ADMIN_URL}
  cliente:
    url: ${FRONTEND_CLIENTE_URL}