spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/click-barber_db
    username: clbb
    password: clbb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

flyway:
  enabled: true
  validateMigrationNaming: true
  locations: classpath:db/migration

jwt:
  secret: secretkeyclickbarbertestespringbootcomjava1234