name: Docker Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.1.5

      - name: Login to Docker hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }} 

      - name: Docker build e push da imagem
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: |
            rafaelbrunof/backend-smart-barber:v${{ github.run_number }}
            rafaelbrunof/backend-smart-barber:latest